### ISSUE TITLE
1.20.5+ Support

### ISSUE THREAD

**Issue by cyrneko** [katelyynn/clover#6]
I heard that there were a lot of changes in 1.20.5 as to how Datapacks work, and for now it seems Clover is broken on those versions because of said changes. Sadly I don't know how to debug datapacks

**Comment by katelyynn** [comment]
fwiw i will look into this soon, it should only require subtle changes if any

**Comment by katelyynn** [comment]
lol turns out i accidentally wrote the wrong word in the code whenever i was updating it so that is fixed 😭 new ver will be out soon

**Comment by katelyynn** [comment]
https://github.com/katelyynn/clover/releases/tag/2024.0714

**Comment by katelyynn** [comment]
thank u for reporting :3
