### ISSUE TITLE
functions not loading in 1.21; changed folder names

### ISSUE THREAD

**Issue by MsFlutter** [katelyynn/clover#7]
in the new 1.21 update (and probably a couple snapshots too) the names of folders in data packs were changed, so "functions" has to be renamed to "function" or none of your functions will work. 

They also did this with some other folders too. Namely, structures, advancements, recipes, loot_tables, predicates, item_modifiers, functions, and tags/functions are all now singular instead of plural

You can find them at [https://minecraft.wiki/w/Java_Edition_1.21#Changes](https://minecraft.wiki/w/Java_Edition_1.21#Changes) (ctrl+f "Affected directories") 

[Helpful reddit thread where I found this solution if you want it](https://www.reddit.com/r/MinecraftCommands/comments/1dfcuxd/datapack_not_working_on_1210_help/)

**Comment by MsFlutter** [comment]
nvm just realized I forgot to look for closed issues so this is a duplicate lol sorry

**Comment by katelyynn** [comment]
don't worry i've actually not done that yet as i hadn't realised until last night so i'll update it in a bit thank u

**Comment by katelyynn** [comment]
(is now done in the latest release)
