### ISSUE TITLE
nickname in chat/tag?

### ISSUE THREAD

**Issue by goose-soop** [katelyynn/clover#8]
like how the pronouns are added, would you be able to implement a way to change the username to a nickname someone sets?

**Comment by goose-soop** [comment]
also this is totally unrelated, but the 1.21 version works on 1.21.1 if you wanna add that as a tag as well

**Comment by katelyynn** [comment]
ive not touched my minecraft projects in a long while but afaik this isnt possible sadly, you would need a nickname plugin on a server that doesnt just completely rewrite usernames and ignore vanilla standards (aka. one that respects vanilla teams)
